version: "3.8"

services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - /home/gustavo/teste_tecnico_retta:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    restart: unless-stopped
    command: >
      bash -c "a2enmod rewrite && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

